#
# Copyright (c) 2022 Darryl deHaan
# SPDX-License-Identifier: MIT
#

# enable display drivers
CONFIG_ZMK_DISPLAY=y

#EXT POWER
#CONFIG_ZMK_EXT_POWER=y
#BLE-passkey
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_EXT_POWER=y
#BLE-clean
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

#EC11 enable
CONFIG_ZMK_MOUSE=y

# 3 profiles (n+2)
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=3

# display
CONFIG_BT_BAS=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096

# Enable SPI
CONFIG_SPI=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_MOUSE=y
#OLD
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=n
CONFIG_PMW3610=y
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=1500
CONFIG_PMW3610_REPORT_INTERVAL_MIN=16

CONFIG_PMW3610_IGNORE_FIRST_N=15
CONFIG_PMW3610_IGNORE_AFTER_REST=n
CONFIG_PMW3610_ANTI_WARP=y
CONFIG_PMW3610_ANTI_WARP_THRES=100
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y


# BLE name
CONFIG_BT_DEVICE_NAME="Crosses Dongle"

# ZMK internal name
CONFIG_ZMK_KEYBOARD_NAME="Crosses"

# USB / Studio
CONFIG_USB_DEVICE_PRODUCT="Crosses Dongle"

# Display timeout - 5 minutes (300000 milliseconds)
CONFIG_ZMK_IDLE_TIMEOUT=300000
# Disable deep sleep (USB powered, always on)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2147483647